description: >
  This is a sample executor using Docker and Node.
docker:
  - image: 'unityci/editor:<<parameters.tag>>'
parameters:
  tag:
    default: 2021.2.7f1-mac-mono-0.15
    description: >
      Pick a specific unityci/editor image variant:
      https://hub.docker.com/r/unityci/editor/tags
    type: string
